version: '3.8'

services:
  #Database MongoDB
  mongodb:
    image: mongo:latest
    container_name: plato-mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - plato-network


  # Backend Service (Go)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plato-backend
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - plato-network

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plato-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - plato-network
    depends_on:
      - backend

  # Nginx Reverse Proxy (Optional - untuk production)
  nginx:
    image: nginx:alpine
    container_name: plato-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - plato-network
    depends_on:
      - frontend
      - backend

networks:
  plato-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local